spring:
  application:
    name: msa-service-coffee-member
      #Config Server
  cloud:
      config:
        url: http://localhost:8888
        name: msa-architecture-config-server

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
